[project]
name = "envkit"
version = "0.7.0.post1"
description = "A lightweight, strongly-typed environment variable parser focused on explicit configuration and predictable behavior, inspired by environs."
authors = [{ name = "Théo Guérin", email = "contact@theo-guerin.dev" }]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Typing :: Typed",
]
requires-python = ">=3.12"

[project.urls]
Homepage = "https://codeberg.org/theo-guerin/envkit"
Repository = "https://codeberg.org/theo-guerin/envkit"
Issues = "https://codeberg.org/theo-guerin/envkit/issues"

[dependency-groups]
dev = [
  "ruff>=0.14.9",
  "basedpyright>=1.36.1",
  "pytest>=9.0.2",
  "pytest-cov>=7.0.0",
  "mypy>=1.19.1",
  "ty>=0.0.8",
  "pyrefly>=1.1.1",
]

[tool.uv]
exclude-newer = "7 days"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = "--cov"

[tool.coverage.run]
source = ["src/envkit"]

[tool.coverage.report]
fail_under = 100

[tool.ruff.lint]
select = ["I", "F", "E", "W", "UP", "B", "SIM", "RUF"]

[tool.basedpyright]
typeCheckingMode = "all"

[tool.mypy]
strict = true
exclude = '\.venv'

[tool.pyrefly]
project-includes = ["src/**/*.py"]
preset = "strict"
